[package]
name = "factorio-mod-downloader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
serde_json = "1.0.75"
serde_yaml = "0.8.13"
error-chain = "0.12.4"
